apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
spec:
  address: http://127.0.0.1:8200
  credentials:
    source: Secret
    secretRef:
      name: vault-creds
      namespace: vault
      key: token
